title: 个人博客 - zlzhang0122
name: zlzhang0122的个人博客
description: zlzhang0122的个人博客
baseurl: "/"
github_username:  zlzhang0122

paginate: 10

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
author: zlzhang0122

host: 0.0.0.0

